basePath: /
definitions:
  model.BaseResponse:
    properties:
      data: {}
      description:
        type: string
      message:
        type: string
      status:
        type: string
      success:
        type: boolean
    type: object
  model.LoginRequest:
    properties:
      password:
        default: P@$$w0rd2o24
        type: string
      username:
        default: superadmin
        type: string
    type: object
  model.RefreshRequest:
    properties:
      token:
        type: string
    required:
    - token
    type: object
  model.UserCreateRequest:
    properties:
      birth_date:
        type: string
      full_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      role_id:
        type: integer
      username:
        type: string
    required:
    - birth_date
    - full_name
    - password
    - phone_number
    - username
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Application
  title: EduSync API
  version: "1.0"
paths:
  /api/minio/upload-image:
    post:
      consumes:
      - application/json
      - multipart/form-data
      description: Upload Image
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/octet-stream
      - image/png
      - image/jpeg
      - image/jpg
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - ApiKeyAuth: []
      tags:
      - Minio
  /api/roles:
    get:
      consumes:
      - application/json
      description: Get List Role
      parameters:
      - default: 10
        description: pageSize
        in: query
        name: pageSize
        required: true
        type: integer
      - default: 1
        description: page
        in: query
        name: page
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: Get List Role
      tags:
      - Role
  /api/users:
    post:
      consumes:
      - application/json
      description: Create User
      parameters:
      - description: Create User
        in: body
        name: create
        required: true
        schema:
          $ref: '#/definitions/model.UserCreateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.BaseResponse'
      security:
      - ApiKeyAuth: []
      summary: Create User
      tags:
      - User
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login User
      parameters:
      - description: Login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.BaseResponse'
      summary: Login User
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh Token
      parameters:
      - description: Refresh Token
        in: body
        name: token
        required: true
        schema:
          $ref: '#/definitions/model.RefreshRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/model.BaseResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/model.BaseResponse'
      summary: Refresh Token
      tags:
      - Auth
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
